# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YnPEwh8S0G7mhLB51xfj4upmHbwrF9PK
"""

from google.colab import files
a=files.upload()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

data=pd.read_csv("weight-height.csv")
data['Gender'].replace('Female',0,inplace=True)
data['Gender'].replace('Male',1,inplace=True)

data.info()
data.describe()
data.isnull().sum()

x=data.iloc[:,0:2].values
y=data.iloc[:,2].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

reg=LinearRegression()
reg.fit(x_train,y_train)

pred_y=reg.predict(x_test)
pred_y[[0,67]]

print('r square error=',metrics.r2_score(y_test,pred_y))
print('mean square error=',metrics.mean_squared_error(y_test,pred_y))
print('mean absolute error=',metrics.mean_absolute_error(y_test,pred_y))

gender=int(input())
height=int(input())
prediction=reg.predict([[gender,height]])
prediction









